<?php
//$ID$
/**
 @file
 Modulo para mostrar mis postulaciones
*/

function postulaciones_block_info(){
	$blocks = Array();
	$blocks['info'] = Array(
		'info' => t('Bloque mis Postulaciones')
	);
	return $blocks;
}

function postulaciones_block_view($delta = ''){
	$block = Array();
	$block['subject'] = t('Mis Postulaciones');
	$block['content'] = mypostulaciones();
	return $block;
}

function mypostulaciones(){
	global $user;
	$id_usuario = $user->uid;
	if ($id_usuario == 0) {
		return '<span class="" style="color:red">No esta logueado</span>';		
	} 
	$postulaciones=GetPostulaciones($id_usuario);	
	if(count($postulaciones)==0)
		return '<span class="" style="color:red">No se ha postulado a ninguna oferta.</span>';	
	$final='';
	foreach($postulaciones as $p){
		$result = db_query("select alias from url_alias where url_alias.source='node/".$p->vid."'")->fetchAll();
		$url=file_create_url($result[0]->alias);
		$value=node_load($p->vid);
		
		$final.='<a href="'.$url.'"><span style="font-weight:700;color:#E55C00">'.$p->title.'</span></a><br>';
					
		if(isset($value->field_empresa['und'][0]['value'])){
			$empresa=$value->field_empresa['und'][0]['value'];
			$final.='<em>'.$empresa.'</em><br>';
		}
	}
	return $final;
}


function GetPostulaciones($idusuario){
	
	$result = db_query("select * FROM node where node.`status`=1 and type='oferta_laboral' and nid in (select nid from oferta_candidato where uid=".$idusuario.")")->fetchAll();
    return $result;
}




